# Test scenario for AIB action
on:
  push:
    paths:
    - '**rai-msdn-test-workflow.yml'

jobs:      
  job1:
    runs-on: ubuntu-latest
    name: createCustomImage
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - shell: bash
      run: mkdir -p installScripts
    
    - shell: bash
      run: |
          echo "echo Installing World... " > installScripts/install-world.sh |
          echo "echo Installing Universe... " > installScripts/install-universe.sh
    
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_MSDN}}
    
    - name: aib action
      id: aib
      uses: ./
      with:
        location: 'eastus2'
        resourceGroupName: 'raiaib-rg'
        sourceOSType: 'linux'
        sourceImageType: 'marketplace'
        sourceImage: Canonical:UbuntuServer:18.04-LTS:latest
        customizerSource: '/home/runner/work/imageBuilder/installScripts'
        distributorType: 'sharedgalleryimage'
        distResourceId: '/subscriptions/0217f681-f72a-4f74-ba27-41aa5e987de0/resourceGroups/raiaib-rg/providers/Microsoft.Compute/galleries/raiSIG_AIB_Test/images/rai-custom-linux'
        distLocation: 'eastus2'

    - name: print aib output
      run: echo output from aib ${{ steps.aib.outputs.imagebuilderRunStatus }} ${{ steps.aib.outputs.runOutputName }} ${{ steps.aib.outputs.customImageURI }}
